### ISSUE TITLE
unable to podupdate

### ISSUE THREAD

**Issue by bigParis** [growingio/GrowingSDK-iOS-GrowingAutoTrackKit#3]
[!] Error installing GrowingAutoTrackKit
[!] /usr/local/bin/git clone https://github.com/growingio/GrowingSDK-iOS-GrowingAutoTrackKit.git /var/folders/zj/kvv5w2x578l9qyfx8lfy2y5m0000gn/T/d20191009-1813-jupmp8 --template= --single-branch --depth 1 --branch 2.8.4

Cloning into '/var/folders/zj/kvv5w2x578l9qyfx8lfy2y5m0000gn/T/d20191009-1813-jupmp8'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed

**Comment by NanNanCHN** [comment]
@bigParis 您好 昨天和今天都有尝试过pod update 我们这边没有问题,您的问题原因可能很多,建议您搜索error原因尝试下不同的解决方案,有可能是网络问题 有可能是pods问题 有可能是git config的问题
